INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with watchdog (windowsapi)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 141-543-928
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with watchdog (windowsapi)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 141-543-928
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:21] "GET / HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:27] "[35m[1mPOST / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:27] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:27] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:27] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:28] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:32] "[35m[1mPOST / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:32] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:32] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:33] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:33] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:39] "[35m[1mPOST / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:39] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:39] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:47] "[35m[1mPOST / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:47] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:47] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:47] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:56:48] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug: * Detected change in 'c:\\Users\\tolen\\OneDrive\\Desktop\\Project\\app.py', reloading
INFO:werkzeug: * Detected change in 'c:\\Users\\tolen\\OneDrive\\Desktop\\Project\\app.py', reloading
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://localhost:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:59:39] "GET / HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
ERROR:app:Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 540, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\tolen\OneDrive\Desktop\Project\app.py", line 47, in index
    user = auth.sign_in_with_email_and_password(email, password)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 86, in sign_in_with_email_and_password
    raise_detailed_error(request_object)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 544, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w] {
  "error": {
    "code": 400,
    "message": "INVALID_LOGIN_CREDENTIALS",
    "errors": [
      {
        "message": "INVALID_LOGIN_CREDENTIALS",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1760, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1758, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1734, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\tolen\OneDrive\Desktop\Project\app.py", line 52, in index
    if e.response.status_code == 400:
AttributeError: 'NoneType' object has no attribute 'status_code'
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 13:59:43] "[35m[1mPOST / HTTP/1.1[0m" 500 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w HTTP/1.1" 400 None
ERROR:app:Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 540, in raise_detailed_error
    request_object.raise_for_status()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\tolen\OneDrive\Desktop\Project\app.py", line 47, in index
    user = auth.sign_in_with_email_and_password(email, password)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 86, in sign_in_with_email_and_password
    raise_detailed_error(request_object)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\pyrebase\pyrebase.py", line 544, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyAF25avieiXm9XIZezYaL1JCEAux0-Gl1w] {
  "error": {
    "code": 400,
    "message": "INVALID_LOGIN_CREDENTIALS",
    "errors": [
      {
        "message": "INVALID_LOGIN_CREDENTIALS",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1760, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1758, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tolen\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1734, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\tolen\OneDrive\Desktop\Project\app.py", line 52, in index
    if e.response.status_code == 400:
AttributeError: 'NoneType' object has no attribute 'status_code'
INFO:werkzeug:127.0.0.1 - - [20/Mar/2024 14:00:01] "[35m[1mPOST / HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://localhost:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
